### ISSUE TITLE
Unable to force reboot/shutdown with keycombination (long press)

### ISSUE THREAD

**Issue by ghost** [SamarV-121/android_kernel_realme_mt6785#1]
Hi, I have a problem. I using a Pixel Experience custom rom and I unable to force reboot/shutdown my phone with any of the long press keycombinations like volume up+power or volume down+power or power or volume up+volume down+power. I am not android developer but I think this issue is related with the kernel. Please correct me If not.

**Comment by SamarV-121** [comment]
Blame realme

**Comment by ghost** [comment]
But the force reboot is working with the [realme kernel](https://github.com/realme-kernel-opensource/realme6-kernel-source), I checked that with another custom rom which is using that.
And someone say that he is successfully reboots his phone with pressing all button for 10 sec, with your LOS build. I installed your build too, to test it but unfortunately not working like other roms. Maybe the issue is, my phone is EU variant?

**Comment by SamarV-121** [comment]
it will be fixed in upcoming build

9cefc4cdf8c2b06ec2eb2540c1e68a136bfc7ce7

**Comment by ghost** [comment]
Thank you!
